# Generated by Django 3.2 on 2024-04-28 07:27

import Graph.namingr
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('icon', models.CharField(db_index=True, default='mdi mdi-text', max_length=150)),
                ('thumbnail', models.ImageField(blank=True, default='default/topic/thumbnail/default.png', upload_to=Graph.namingr.get_topic_picture_path)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('color', models.CharField(blank=True, default='#75d317', max_length=150)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='_Graph_topic_parent_+', to='Graph.Topic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
