# Generated by Django 3.2 on 2024-04-28 07:26

import Content.namingr
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Graph', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('icon', models.ImageField(blank=True, default='default/app/icon/icon.png', max_length=5000, upload_to=Content.namingr.get_app_icon_path)),
                ('thumbnail', models.ImageField(blank=True, default='default/app/thumbnail/thumbnail.png', max_length=5000, upload_to=Content.namingr.get_app_thumbnail_path)),
                ('url', models.URLField(blank=True, max_length=250)),
                ('color', models.CharField(blank=True, default='#2a6602', max_length=150)),
                ('background_color', models.CharField(blank=True, default='#ccedab', max_length=150)),
                ('views_counter', models.IntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_category', to='Graph.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='app_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, max_length=5000, upload_to=Content.namingr.get_appcarousel_media_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Content.app')),
            ],
        ),
    ]
